version: '3.8'

services:
  app:
    build: .
    container_name: rechtmaschine-app
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - caddy
    volumes:
      - ./app.py:/app/app.py
      - downloaded_sources:/app/downloaded_sources

volumes:
  downloaded_sources:

networks:
  caddy:
    external: true
    name: caddy
